# Generated by Django 2.1.1 on 2018-09-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180918_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
